Решение 3 задач и написание теста на функцию convertBytesToHuman - dz1
zaebbb/2024-2-VK-EDU-Frontend-V-Mihailov pull request #2
Opened 2024-09-18 12:26 UTC by zaebbb

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Реализованы 3 функции (convertBytesToHuman, correctSentence, nonUniqueElements)
* Написаны тесты на функцию convertBytesToHuman (Максимальный упор реализовал до GB)

2024-09-18 14:32 UTC, 1MarBur1 requested changes

2024-09-18 14:32 UTC, 1MarBur1 commented on convertBytesToHuman.js
выглядит тяжеломасштабируемо, что если мы хотим выводить тера-, пета- байты?

давай придумаем единый алгоритм, как можно сделать для любого количества байт, с возможностью простого масштабирования

посмотри какая закономерность есть при переходе от байтов к килобайтам, от килобайтов к мегабайтам и тд

2024-09-18 14:32 UTC, 1MarBur1 commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false)
давай будем использовать точки с запятой, пройдись по проекту и посмотри везде

2024-09-18 15:09 UTC, zaebbb commented
# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Добавил точки с запятой по всему проекту
* Сделал функцию convertBytesToHuman более универсальной и масштабируемой через рекурсию

2024-09-18 19:10 UTC, 1MarBur1 requested changes

2024-09-18 19:10 UTC, 1MarBur1 commented on convertBytesToHuman.js
Давай реализуем через цикл, это будет сильно быстрее, чем рекурсия)

2024-09-19 07:53 UTC, zaebbb commented
# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Переписал рекурсию на цикл

2024-09-20 22:29 UTC, 1MarBur1 requested changes

2024-09-20 22:29 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +export default function convertBytesToHuman(bytes, currentByteUnit = BYTE_UNITS[0]) {
разве нам нужно передавать currentByteUnit аргументом? давай придерживаться YAGNI, и не будем делать то, что скорее всего не пригодится

2024-09-20 22:29 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +    bytes === -Infinity
1, 3, 4, 5 можно проверить с Number.isFinite()

суть та же, выглядит лучше)

2024-09-20 22:29 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +const formatByteToHuman = (bytes, byteUnit) => `${formatNumber(bytes)} ${byteUnit}`;
зачем нам эти функции? Они просто формируют строки/числа) не нужно засорять память, когда мы можем просто присвоить это значение переменной внутри convertBytesToHuman()

2024-09-24 11:58 UTC, 1MarBur1 requested changes

2024-09-24 11:58 UTC, 1MarBur1 commented on convertBytesToHuman.js
Отлично! Это уже очень похоже на правду, но последнее замечание, нужно ли нам хранить именно currentByteUnit? Почему бы не хранить просто index и при выводе сделать BYTE_UNITS[index] ? тогда не придется делать .indexOf() который занимает O(n)

2024-09-24 13:08 UTC, zaebbb commented
Убрал из функции indexOf и заменил значение индексом

2024-09-24 18:58 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-09-25 20:44 UTC, martinkomitsky approved these changes
12!

2024-09-25 20:44 UTC, merged