Dz2
zaebbb/2024-2-VK-EDU-Frontend-V-Mihailov pull request #3
Opened 2024-09-27 09:33 UTC by zaebbb

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Реализовал страницу чата, взяв за основу пример из макета
* Доработал конфигурацию webpack для работы с изображениями
* Подключил Google иконки
* Подключил шрифт Montserrat
* Задеплоил проект
* Сделал отдельную ветку gh-pages
* Разработал функционал в соответствии с ДЗ

2024-10-01 17:35 UTC, 1MarBur1 requested changes

2024-10-01 17:35 UTC, 1MarBur1 commented on simple-chat/src/index.js
сейчас при отправке сообщения происходит ререндер всего блока сообщений, можем ли мы это как-то предотвратить?

2024-10-01 17:35 UTC, 1MarBur1 commented on simple-chat/src/index.js
> +    `;
Давай сделаем какую-то функцию в которую вынесем темплейт сообщения и пропсами будем передавать данные

2024-10-02 12:02 UTC, zaebbb commented
1. Заменил inndexHTML на appendChild
2. Вынес формирование шаблона сообщения в отдельную функцию

2024-10-03 12:30 UTC, 1MarBur1 approved these changes
@HaseProgram @martinkomitsky @kgrechin approved

2024-10-03 18:10 UTC, HaseProgram approved these changes
12!

2024-10-03 18:11 UTC, merged