Разделение скриптов, создание новой страницы - dz3
zaebbb/2024-2-VK-EDU-Frontend-V-Mihailov pull request #4
Opened 2024-10-09 12:05 UTC by zaebbb

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
*
* 
*

2024-10-13 09:49 UTC, 1MarBur1 requested changes
Давай положим моки в localstorage, чтобы брать данные из одного места, 

В рамках этого задания нужно реализовать создание нового чата, открытие конкретного (просмотр сообщений именно того чата, который открыли)

2024-10-15 15:58 UTC, zaebbb commented
* Создал функцию которая создает мок-данные в localStorage
* Сделал универсальный список чатов
* Доработал добавление сообщения в определенный чат
* Доработал список чатов

2024-10-24 21:20 UTC, 1MarBur1 requested changes

2024-10-24 21:20 UTC, 1MarBur1 commented on simple-chat/src/index.js
> +      }
если введу " " и нажму enter - сообщение отправится, хотя не должно

2024-10-24 21:20 UTC, 1MarBur1 commented on simple-chat/src/chat.html
> +          </button>
По нажатию на кнопку назад нужно проводить редирект на домашнюю страницу.

2024-10-24 21:20 UTC, 1MarBur1 commented on simple-chat/src/chat.html
> +              </span>
Давай будем выводить имя пользователя из localStorage

2024-10-24 21:27 UTC, 1MarBur1 commented
В идеале - кнопка создания чата должна работать и действительно создавать новый чат

2024-10-29 11:41 UTC, zaebbb commented
Внес доработки, добавил функцию нового чата

2024-10-30 19:51 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-10-31 06:37 UTC, HaseProgram approved these changes
Класс, 12!

2024-10-31 06:37 UTC, merged