Dz5
zaebbb/2024-2-VK-EDU-Frontend-V-Mihailov pull request #6
Opened 2024-10-31 10:51 UTC by zaebbb

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
*
*
* Переписал весь проект на react
* Восстановил функциональность
* Сделал 1 общий глобальный state 
* Подредактировал конфигурацию package.json в ./react-chat

2024-11-10 11:19 UTC, martinkomitsky commented
@1MarBur1 ждём комменты

2024-11-28 06:38 UTC, Ivan-Bir requested changes
Привет! Подхвачу твои MR'ы до конца курса
Нашел ссылку на деплой https://zaebbb.github.io/2024-2-VK-EDU-Frontend-V-Mihailov/ - оставляй пж её в след раз в описании MR, чтобы не искать (это реально zaebbb)

Заметил ряд важных моментов в UI
1) Не совсем корректно приложение запускается. При первом запуске пустой экран. Только после перезагрузки появляются
2) Ломается приложение при перезагрузке вкладки
3) Ошибки при попытке создать новый чат
![image](https://github.com/user-attachments/assets/39b866b3-4c56-4d2b-afd1-11cc21ee8b7c)
4) Не работает кнопка поиска, (кажется, что к 5-му дз она уже должна быть)
Менее критичные, но важные точки зрения UX:
- Не работающих кнопок в приложении быть не должно, если уже не охота убирать, то можно повесить стиль cursor: not-allowed;
- Нет кнопки отправки сообщения через ЛКМ - не всегда хочется отправлять с клавы
- Длинное слово не бьется на строки, а вылезает за края верстки
- Предлагаю дать имя сервису и заменить стандартную фавиконку и заголовок вкладки на авторские

2024-11-28 06:38 UTC, Ivan-Bir commented on simple-chat/src/components/messageHtml.js
>    messageElement.innerHTML = `
Если ты переехал на react, то этого уже быть не должно

2024-11-28 06:38 UTC, Ivan-Bir commented on react-chat/src/lib/getRandomFullName.js
> +export const getRandomFullname = () => {
Такой код лучше класть в директорию `__mocks__`

2025-01-10 13:25 UTC, martinkomitsky commented
@Ivan-Bir

2025-01-12 14:01 UTC, Ivan-Bir approved these changes
По моим предыдущим замечания поправлено только 2 пункта.
Из нового заметил, что не ставится пробел в инпуте(
Пусть формально дз на реакт переписано, но, по-хорошему, нужно дорабатывать

2025-01-12 19:44 UTC, martinkomitsky commented
10

2025-01-12 19:44 UTC, merged